Update rungrafana.sh
I was getting error

Error: ✗ Plugin not found (Grafana v9.0.2 linux-amd64)

As per documentation https://grafana.com/grafana/plugins/grafana-azure-monitor-datasource/?tab=installation

This plugin is included with Grafana and does not require installation. Woo.

Removing the Plugin works.